version: '3.8'
services:
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK.relative=1


  clickhouse:
    hostname: clickhouse
    container_name: clickhouse
    volumes:
      - ./clickhouse-data:/var/lib/clickhouse
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9001:9000"
      - "9942:9942"
    environment:
      - CLICKHOUSE_DB=test
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin


  link_gen:
    container_name: link_generator
    hostname: link_generator
    build: /link_gen
    depends_on:
      - clickhouse
      - rabbitmq


  news_parser:
    container_name: news_parser
    hostname: news_parser
    build: /news_parser
    depends_on:
      - clickhouse
      - rabbitmq

  remove_repeat:
    container_name: remove_repeat
    hostname: remove_repeat
    build: /remove_repeat
    depends_on:
      - clickhouse
      - rabbitmq

  managment:
    container_name: managment
    hostname: managment
    build: /managment
    depends_on:
      - rabbitmq

