version: '3.8'
services:
  rabbitmq:
    ports:
      - "5672:5672"
      - "15972:15972"
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK.relative=1
    networks:
      default:
        ipv4_address: 172.16.1.3

  clickhouse:
    hostname: clickhouse
    container_name: clickhouse
    volumes:
      - ./clickhouse-data:/var/lib/clickhouse
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9001:9000"
      - "9942:9942"
    networks:
      default:
        ipv4_address: 172.16.1.2

  link_gen:
    container_name: link_generator
    hostname: link_generator
    build: /link_gen
    networks:
      default:
        ipv4_address: 172.16.1.4
    depends_on:
      - clickhouse
      - rabbitmq


  news_parser:
    container_name: news_parser
    hostname: news_parser
    build: /news_parser
    networks:
      default:
        ipv4_address: 172.16.1.5
    depends_on:
      - clickhouse
      - rabbitmq

  remove_repeat:
    container_name: remove_repeat
    hostname: remove_repeat
    build: /remove_repeat
    networks:
      default:
        ipv4_address: 172.16.1.6
    depends_on:
      - clickhouse
      - rabbitmq

  managment:
    container_name: managment
    hostname: managment
    build: /managment
    networks:
      default:
        ipv4_address: 172.16.1.7
    depends_on:
      - rabbitmq




networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
